name: ml_cuda12.2_py39
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - astor
  - asttokens
  - async-lru
  - attrs
  - babel
  - base58
  - bleach
  - bottleneck
  - brotli-python
  - certifi
  - charset-normalizer
  - coloredlogs
  - comm
  - contourpy
  - cryptography
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - executing
  - fastapi
  - filelock
  - gmpy2
  - h11
  - httpcore
  - httpx
  - humanfriendly
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - jmespath
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - markupsafe
  - matplotlib
  - matplotlib-inline
  - mistune
  - mpmath
  - mysql
  - nbclient
  - nbconvert-core
  - nbformat
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pillow
  - platformdirs
  - prometheus_client
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pydeck
  - pygments
  - pympler
  - pyparsing
  - pyqt
  - pysocks
  - python-dateutil
  - python-fastjsonschema
  - python-flatbuffers
  - python-json-logger
  - python-tzdata
  - pytorch
  - pytorch-cuda
  - pytorch-mutex
  - pytz
  - pyyaml
  - pyzmq
  - referencing
  - reportlab
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - s3transfer
  - scikit-learn
  - seaborn
  - semver
  - send2trash
  - six
  - smart_open
  - sniffio
  - soupsieve
  - stack_data
  - starlette
  - terminado
  - tinycss2
  - tomli
  - tornado
  - traitlets
  - tzdata
  - tzlocal
  - unicodedata2
  - urllib3
  - validators
  - wcwidth
  - webencodings
  - websocket-client
  - widgetsnbextension
  - zipp
  - pip:
      - accelerate
      - adjusttext
      - aiohttp
      - altair
      - annotated-types
      - black
      - blinker
      - blis
      - cachetools
      - catalogue
      - cffi
      - click
      - cloudpathlib
      - cloudpickle
      - colorama
      - colorspacious
      - confection
      - cymem
      - dataclasses-json
      - datasets
      - dill
      - distro
      - docker
      - dotenv
      - dtale
      - et-xmlfile
      - exifread
      - flameprof
      - frozenlist
      - fsspec
      - future
      - gitpython
      - grad-cam
      - humanize
      - imageio
      - ipdb
      - itsdangerous
      - jaxtyping
      - joblib
      - jsonpatch
      - jsonpointer
      - jupytext
      - kaleido
      - kornia
      - langcodes
      - langsmith
      - lazy-loader
      - lightning-utilities
      - lz4
      - marisa-trie
      - markdown-it-py
      - marshmallow
      - missingno
      - multidict
      - multiprocess
      - murmurhash
      - mypy-extensions
      - narwhals
      - nbstripout
      - nodeenv
      - openpyxl
      - orjson
      - pandera
      - pathspec
      - patsy
      - pluggy
      - plum-dispatch
      - preshed
      - propcache
      - psycopg
      - pyarrow
      - pydantic
      - pydantic-settings
      - pymupdf
      - pypdfium2
      - pyperclip
      - pyright
      - pytest
      - pytest-timeout
      - python-dotenv
      - python-slugify
      - rapidfuzz
      - rawpy
      - regex
      - requests-toolbelt
      - retrying
      - rich
      - safetensors
      - scipy
      - setuptools
      - shellingham
      - simplejson
      - smart-open
      - squarify
      - srsly
      - statsmodels
      - strsimpy
      - sympy
      - tabulate
      - tenacity
      - termcolor
      - text-unidecode
      - threadpoolctl
      - timm
      - toml
      - toolz
      - torchmetrics
      - tqdm
      - ttach
      - typeguard
      - typer
      - typing-extensions
      - typing-inspect
      - wasabi
      - watchdog
      - weasel
      - werkzeug
      - wheel
      - wrapt
      - xarray
      - xlrd
      - xxhash
      - yarl
      - zstandard