services:
  postgres:
    image: postgres:16
    container_name: query_scheduler_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tpcds
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA_HOST_PATH:-./pgdata}:/var/lib/postgresql/data